const HANDLE_CHANGE = "HANDLE_CHANGE"
const HANDLE_REGISTRATION = "HANDLE_REGISTRATION"
const HANDLE_LOGIN = "HANDLE_LOGIN"
const RELOAD = "RELOAD"



export {
    HANDLE_CHANGE,
    HANDLE_REGISTRATION,
    HANDLE_LOGIN,
    RELOAD,
}
