const HANDLE_CHANGE = "HANDLE_CHANGE"
const HANDLE_REGISTRATION = "HANDLE_REGISTRATION"
const HANDLE_LOGIN = "HANDLE_LOGIN"
const RELOAD = "RELOAD"
const LOG_OUT = "LOG_OUT"




export {
    HANDLE_CHANGE,
    HANDLE_REGISTRATION,
    HANDLE_LOGIN,
    RELOAD,
    LOG_OUT,
}
