const HANDLE_CHANGE = "HANDLE_CHANGE"
const HANDLE_SUBMIT = "HANDLE_SUBMIT"
const HANDLE_LOGIN = "HANDLE_LOGIN"
const RELOAD = "RELOAD"



export {
    HANDLE_CHANGE,
    HANDLE_SUBMIT,
    HANDLE_LOGIN,
    RELOAD,
}
